### ISSUE TITLE
直播的时候会出现花屏

### ISSUE THREAD

**Issue by adow** [runner365/GPUImageRtmpPush#1]
我在使用 GPUImage 和 RtmpLivePushSDK 进行直播推流的时候（服务器是 SRS），有的时候看到正常，很多时候会看到花屏，有时后面几秒就好了，有时就直接干脆卡住不动了。请问这是什么原因呢？

**Comment by adow** [comment]
我去掉了滤镜，尝试使用 GPUImageRawDataOutput 或者 GPUImageMovieWriterEx 都出现了这样的问题，开始我以为是我代码中集成的时候有地方配置问题。然后我运行了 GPUImageRtmpPush 这个项目推流到我的服务器上也有这样的问题。

**Comment by runner365** [comment]
请告知使用的分辨率，码率，帧率。

**Comment by runner365** [comment]
分辨率,速率配对关系:
1, 720x1280:至少1.5mbps;
2, 540x960: 至少800kbps;
3, 360x640: 至少:600kbps;
请检查现场网络上行速率环境是否和分辨率匹配。
